services:
  product-service-repo:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: product_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_service -d products"]
      interval: 10s
      timeout: 10s
      retries: 5

  product_service_migrations:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://product_service:password@product-service-repo:5432/products?sslmode=disable",
      "up"
    ]
    volumes:
      - ./services/product-service/migrations:/migrations
    depends_on:
      product-service-repo:
        condition: service_healthy
    restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      -ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1